### ISSUE TITLE
Try to run sample data

### ISSUE THREAD

**Issue by Bancherd-DeLong** [cuhk-nlp/BioKMNER#1]
HI:

Interesting project.  I tried to follow your example and "run.sh" and the following error occured.  Any suggestions, please?
`(base) bancherd@bancherd-desktop9:~/BioKMNER$ source run.sh
mkdir: cannot create directory ‘logs’: File exists
mkdir: cannot create directory ‘results’: File exists
Namespace(bert_model='/home/bancherd/BioKMNER/biobert_pyt/', cache_dir='', data_dir='./data/sample_data/', do_eval=True, do_lower_case=False, do_train=True, eval_batch_size=16, feature_flag='pos', fp16=False, gradient_accumulation_steps=1, learning_rate=2e-05, local_rank=-1, loss_scale=0, max_seq_length=150, max_word_size=150, no_cuda=False, num_train_epochs=3.0, patient=10, restore=False, seed=42, server_ip='', server_port='', train_batch_size=2, warmup_proportion=0.1, word_num_threshold=0, word_num_upper_threshold=100000000)
device: cuda n_gpu: 1, distributed training: False, 16-bits training: False
load word from existing file
# of word: 168
# of labels: 3
Traceback (most recent call last):
  File "run_BioKMNER_pos.py", line 1273, in <module>
    main()
  File "run_BioKMNER_pos.py", line 953, in main
    model.to(device)
AttributeError: 'NoneType' object has no attribute 'to'
`
Thank you!

**Comment by Bancherd-DeLong** [comment]
I think it is due to model loading problem, will check.

**Comment by yuanheTian** [comment]
Hi,

Thanks for asking!

Ask you mentioned, it is a model loading problem; the code fails to load the pre-trained language model (e.g., biobert) because some model files are missing. You can check if the pre-trained language model directory includes the following 3 files.

1. pytorch_model.bin
2. vocab.txt
3. config.json (if this filename doesn't work, you can change its name to bert_config.json and try it again)

**Comment by bhargavi31** [comment]
Hi, 

load word from existing file
# of word: 168
# of labels: 3
Traceback (most recent call last):
  File "run_BioKMNER_pos.py", line 1273, in <module>
    main()
  File "run_BioKMNER_pos.py", line 953, in main
    model.to(device)
AttributeError: 'NoneType' object has no attribute 'to'

I got this error while trying to run "run.sh" file. As mentioned in above comment that pytorch_model.bin file may be missing , could you help to find the file. The pretrained model "BioBERT-Base v1.1 (+ PubMed 1M) " is downloaded from the link provided by you, but the directory does not include above mentioned file. I appreciate your reply on this issue.

Thank you!
